package t08e03;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import t08e03.Disciplina;
import t08e03.Professor;
import t08e03.Aluno;

public class SistemaAcademico extends javax.swing.JFrame {
    private static Professor professores[];
    private static int quantidadeProfessor = 0;
    private static Aluno alunos[];
    private static int quantidadeAluno = 0;
    
    /**
     * Creates new form SistemaAcademico
     */
    public SistemaAcademico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JTabbedPane();
        tabCadastrarProfessor = new javax.swing.JPanel();
        cpNome = new javax.swing.JLabel();
        cpIdade = new javax.swing.JLabel();
        cpEndereco = new javax.swing.JLabel();
        tcpNome = new javax.swing.JTextField();
        tcpIdade = new javax.swing.JTextField();
        tcpEndereco = new javax.swing.JTextField();
        bcpCadastrar = new javax.swing.JButton();
        tabCadastrarAluno = new javax.swing.JPanel();
        caNome = new javax.swing.JLabel();
        caIdade = new javax.swing.JLabel();
        caEndereco = new javax.swing.JLabel();
        caMatricula = new javax.swing.JLabel();
        caCurso = new javax.swing.JLabel();
        caPeriodo = new javax.swing.JLabel();
        tcaNome = new javax.swing.JTextField();
        tcaIdade = new javax.swing.JTextField();
        tcaEndereco = new javax.swing.JTextField();
        tcaMatricula = new javax.swing.JTextField();
        tcaCurso = new javax.swing.JTextField();
        tcaPeriodo = new javax.swing.JTextField();
        bcaCadastrar = new javax.swing.JButton();
        tabExcluirAluno = new javax.swing.JPanel();
        eaNome = new javax.swing.JLabel();
        teaNome = new javax.swing.JTextField();
        beaExcluir = new javax.swing.JButton();
        tabMatricularProfessor = new javax.swing.JPanel();
        mpNome = new javax.swing.JLabel();
        mpDisciplina = new javax.swing.JLabel();
        tmpNome = new javax.swing.JTextField();
        tmpDisciplina = new javax.swing.JTextField();
        bmpMatricular = new javax.swing.JButton();
        tabMatricularAluno = new javax.swing.JPanel();
        maNome = new javax.swing.JLabel();
        maDisciplina = new javax.swing.JLabel();
        tmaNome = new javax.swing.JTextField();
        tmaDisciplina = new javax.swing.JTextField();
        bmaMatricular = new javax.swing.JButton();
        tabCancelarMatriculaAluno = new javax.swing.JPanel();
        cmaNome = new javax.swing.JLabel();
        cmaDisciplina = new javax.swing.JLabel();
        tcmaNome = new javax.swing.JTextField();
        tcmaDisciplina = new javax.swing.JTextField();
        bcmaCancelarMatricula = new javax.swing.JButton();
        tabImprimirAluno = new javax.swing.JPanel();
        biaImprimir = new javax.swing.JButton();
        siaAreaScroll = new javax.swing.JScrollPane();
        taiaAreaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 515));
        setPreferredSize(new java.awt.Dimension(900, 515));
        setSize(new java.awt.Dimension(900, 515));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cpNome.setText("Nome:");

        cpIdade.setText("Idade:");

        cpEndereco.setText("Endereço:");

        bcpCadastrar.setText("Cadastrar");
        bcpCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcpCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCadastrarProfessorLayout = new javax.swing.GroupLayout(tabCadastrarProfessor);
        tabCadastrarProfessor.setLayout(tabCadastrarProfessorLayout);
        tabCadastrarProfessorLayout.setHorizontalGroup(
            tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                        .addComponent(cpNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                        .addComponent(cpIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcpIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCadastrarProfessorLayout.createSequentialGroup()
                        .addComponent(cpEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(tcpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bcpCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(588, Short.MAX_VALUE))
        );
        tabCadastrarProfessorLayout.setVerticalGroup(
            tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpNome)
                    .addComponent(tcpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpIdade)
                    .addComponent(tcpIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpEndereco)
                    .addComponent(tcpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bcpCadastrar)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        Menu.addTab("Cadastrar Professor", tabCadastrarProfessor);

        caNome.setText("Nome:");

        caIdade.setText("Idade:");

        caEndereco.setText("Endereço:");

        caMatricula.setText("Matrícula:");

        caCurso.setText("Curso:");

        caPeriodo.setText("Período:");

        bcaCadastrar.setText("Cadastrar");
        bcaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCadastrarAlunoLayout = new javax.swing.GroupLayout(tabCadastrarAluno);
        tabCadastrarAluno.setLayout(tabCadastrarAlunoLayout);
        tabCadastrarAlunoLayout.setHorizontalGroup(
            tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                        .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caMatricula)
                            .addComponent(caCurso)
                            .addComponent(caPeriodo))
                        .addGap(19, 19, 19)
                        .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcaMatricula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tcaCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tcaPeriodo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                        .addComponent(caNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                        .addComponent(caIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcaIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCadastrarAlunoLayout.createSequentialGroup()
                        .addComponent(caEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(tcaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bcaCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(588, Short.MAX_VALUE))
        );
        tabCadastrarAlunoLayout.setVerticalGroup(
            tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caNome)
                    .addComponent(tcaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caIdade)
                    .addComponent(tcaIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caEndereco)
                    .addComponent(tcaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caMatricula)
                    .addComponent(tcaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caCurso)
                    .addComponent(tcaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caPeriodo)
                    .addComponent(tcaPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bcaCadastrar)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        Menu.addTab("Cadastrar Aluno", tabCadastrarAluno);

        eaNome.setText("Nome:");

        beaExcluir.setText("Excluir");
        beaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beaExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabExcluirAlunoLayout = new javax.swing.GroupLayout(tabExcluirAluno);
        tabExcluirAluno.setLayout(tabExcluirAlunoLayout);
        tabExcluirAlunoLayout.setHorizontalGroup(
            tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabExcluirAlunoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(beaExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabExcluirAlunoLayout.createSequentialGroup()
                        .addComponent(eaNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(teaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(589, 589, 589))
        );
        tabExcluirAlunoLayout.setVerticalGroup(
            tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabExcluirAlunoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eaNome)
                    .addComponent(teaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(beaExcluir)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        Menu.addTab("Excluir Aluno", tabExcluirAluno);

        mpNome.setText("Nome:");

        mpDisciplina.setText("Disciplina:");

        bmpMatricular.setText("Matricular");
        bmpMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmpMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabMatricularProfessorLayout = new javax.swing.GroupLayout(tabMatricularProfessor);
        tabMatricularProfessor.setLayout(tabMatricularProfessorLayout);
        tabMatricularProfessorLayout.setHorizontalGroup(
            tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bmpMatricular, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                        .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mpNome)
                            .addComponent(mpDisciplina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tmpDisciplina)
                            .addComponent(tmpNome, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                .addGap(589, 589, 589))
        );
        tabMatricularProfessorLayout.setVerticalGroup(
            tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpNome)
                    .addComponent(tmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpDisciplina)
                    .addComponent(tmpDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bmpMatricular)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        Menu.addTab("Matricular Professor", tabMatricularProfessor);

        maNome.setText("Nome:");

        maDisciplina.setText("Disciplina:");

        bmaMatricular.setText("Matricular");
        bmaMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmaMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabMatricularAlunoLayout = new javax.swing.GroupLayout(tabMatricularAluno);
        tabMatricularAluno.setLayout(tabMatricularAlunoLayout);
        tabMatricularAlunoLayout.setHorizontalGroup(
            tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMatricularAlunoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bmaMatricular, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(tabMatricularAlunoLayout.createSequentialGroup()
                        .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maNome)
                            .addComponent(maDisciplina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tmaDisciplina)
                            .addComponent(tmaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                .addGap(589, 589, 589))
        );
        tabMatricularAlunoLayout.setVerticalGroup(
            tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMatricularAlunoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNome)
                    .addComponent(tmaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maDisciplina)
                    .addComponent(tmaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bmaMatricular)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        Menu.addTab("Matricular Aluno", tabMatricularAluno);

        cmaNome.setText("Nome:");

        cmaDisciplina.setText("Disciplina:");

        bcmaCancelarMatricula.setText("Cancelar Matrícula");
        bcmaCancelarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcmaCancelarMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCancelarMatriculaAlunoLayout = new javax.swing.GroupLayout(tabCancelarMatriculaAluno);
        tabCancelarMatriculaAluno.setLayout(tabCancelarMatriculaAlunoLayout);
        tabCancelarMatriculaAlunoLayout.setHorizontalGroup(
            tabCancelarMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCancelarMatriculaAlunoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tabCancelarMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcmaCancelarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(tabCancelarMatriculaAlunoLayout.createSequentialGroup()
                        .addGroup(tabCancelarMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmaNome)
                            .addComponent(cmaDisciplina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tabCancelarMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tcmaDisciplina)
                            .addComponent(tcmaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                .addGap(589, 589, 589))
        );
        tabCancelarMatriculaAlunoLayout.setVerticalGroup(
            tabCancelarMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCancelarMatriculaAlunoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tabCancelarMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmaNome)
                    .addComponent(tcmaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCancelarMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmaDisciplina)
                    .addComponent(tcmaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bcmaCancelarMatricula)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        Menu.addTab("Cancelar Matrícula do Aluno", tabCancelarMatriculaAluno);

        biaImprimir.setText("Imprimir Alunos");
        biaImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biaImprimirActionPerformed(evt);
            }
        });

        taiaAreaTexto.setEditable(false);
        taiaAreaTexto.setColumns(20);
        taiaAreaTexto.setRows(5);
        siaAreaScroll.setViewportView(taiaAreaTexto);

        javax.swing.GroupLayout tabImprimirAlunoLayout = new javax.swing.GroupLayout(tabImprimirAluno);
        tabImprimirAluno.setLayout(tabImprimirAlunoLayout);
        tabImprimirAlunoLayout.setHorizontalGroup(
            tabImprimirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabImprimirAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siaAreaScroll)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabImprimirAlunoLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(biaImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        tabImprimirAlunoLayout.setVerticalGroup(
            tabImprimirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabImprimirAlunoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(biaImprimir)
                .addGap(18, 18, 18)
                .addComponent(siaAreaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        Menu.addTab("Imprimir Alunos", tabImprimirAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        boolean condicao = true;
        while(condicao) {
            try {
                int quantidadeTotalProfessores, quantidadeTotalAlunos, i;

                JFrame jFrame = new JFrame();
                String getQuantidadeTotalProfessores = JOptionPane.showInputDialog(jFrame, 
                                                        "Informe a quantidade de professores que serão cadastrados:");
                quantidadeTotalProfessores = Integer.parseInt(getQuantidadeTotalProfessores);

                String getQuantidadeTotalAlunos = JOptionPane.showInputDialog(jFrame, 
                                                    "Agora, informe a quantidade de alunos que serão cadastrados:");
                quantidadeTotalAlunos = Integer.parseInt(getQuantidadeTotalAlunos);

                professores = new Professor[quantidadeTotalProfessores];
                alunos = new Aluno[quantidadeTotalAlunos];
                
                condicao = false;
            } catch(NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null,"A quantidade deve ser numérica!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void bcpCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcpCadastrarActionPerformed
        // TODO add your handling code here:
        String nome = tcpNome.getText();
        int idade = Integer.parseInt(tcpIdade.getText());
        String endereco = tcpEndereco.getText();
        int quantidadeDisciplinasMinistradas = 0;
        
        professores[quantidadeProfessor] = new Professor(nome, idade, endereco, quantidadeDisciplinasMinistradas);;
        quantidadeProfessor++;
        
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "Cadastro realizado com sucesso!");
    }//GEN-LAST:event_bcpCadastrarActionPerformed

    private void bcaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaCadastrarActionPerformed
        // TODO add your handling code here:
        String nome = tcaNome.getText();
        int idade = Integer.parseInt(tcaIdade.getText());
        String endereco = tcaEndereco.getText();
        String matricula = tcaMatricula.getText();
        String curso = tcaCurso.getText();
        int periodo = Integer.parseInt(tcaPeriodo.getText());
        int quantidadeDisciplinasPermitidas = 0;
        
        alunos[quantidadeAluno] = new Aluno(nome, idade, endereco, matricula, curso, periodo, quantidadeDisciplinasPermitidas);
        quantidadeAluno++;
        
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "Cadastro realizado com sucesso!");
    }//GEN-LAST:event_bcaCadastrarActionPerformed

    private void beaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beaExcluirActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        
        String nome = teaNome.getText();
        
        int i = 0;
        while(i < quantidadeAluno && !nome.equals(alunos[i].getNome())) {
            i++;
        }
        
        if (i < quantidadeAluno) {
            for (int k = i; k < quantidadeAluno; k++) {
                alunos[k] = alunos[k+1];
            }
            
            quantidadeAluno--;
            
            JOptionPane.showMessageDialog(jFrame, "Aluno excluído com sucesso!");
        } else {
            JOptionPane.showMessageDialog(jFrame, "Aluno não encontrado.");
        }
    }//GEN-LAST:event_beaExcluirActionPerformed

    private void bmpMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmpMatricularActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        
        String nome = tmpNome.getText();
        String nomeDisciplina = tmpDisciplina.getText();
        
        Disciplina disciplina = new Disciplina(nomeDisciplina);
        
        int i = 0;
        while(i < quantidadeProfessor && !nome.equals(professores[i].getNome())) {
            i++;
        }

        if (i < quantidadeProfessor) {
            if (professores[i].getquantidadeDisciplinasMatriculadas() == 0) {
                boolean condicao = true;
                while(condicao) {
                    try {
                        String getQuantidadeDisciplinas = JOptionPane.showInputDialog(jFrame, 
                                                                "Digite quantas disciplinas o professor deve ser relacionado:");
                        int quantidadeDisciplinas = Integer.parseInt(getQuantidadeDisciplinas);

                        professores[i].setQuantidadeDisciplinasMatriculadas(quantidadeDisciplinas);
                        condicao = false;
                    } catch(NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(null,"A quantidade deve ser numérica!", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            String informe = professores[i].fazMatricula(disciplina);
            JOptionPane.showMessageDialog(jFrame, informe);
        } else {
            JOptionPane.showMessageDialog(jFrame, "Professor não encontrado.");
        }
    }//GEN-LAST:event_bmpMatricularActionPerformed

    private void bmaMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmaMatricularActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        
        String nome = tmaNome.getText();
        String nomeDisciplina = tmaDisciplina.getText();
        
        Disciplina disciplina = new Disciplina(nomeDisciplina);
        
        int i = 0;
        while(i < quantidadeAluno && !nome.equals(alunos[i].getNome())) {
            i++;
        }

        if (i < quantidadeAluno) {
            if (alunos[i].getquantidadeDisciplinasMatriculadas() == 0) {
                boolean condicao = true;
                while(condicao) {
                    try {
                        String getQuantidadeDisciplinas = JOptionPane.showInputDialog(jFrame, 
                                                                "Digite quantas disciplinas o aluno deve ser matriculado:");
                        int quantidadeDisciplinas = Integer.parseInt(getQuantidadeDisciplinas);

                        alunos[i].setQuantidadeDisciplinasPermitidas(quantidadeDisciplinas);
                        condicao = false;
                    } catch(NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(null,"A quantidade deve ser numérica!", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            String informe = alunos[i].fazMatricula(disciplina);
            JOptionPane.showMessageDialog(jFrame, informe);
        } else {
            JOptionPane.showMessageDialog(jFrame, "Aluno não encontrado.");
        }
    }//GEN-LAST:event_bmaMatricularActionPerformed

    private void bcmaCancelarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcmaCancelarMatriculaActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        
        String nome = tcmaNome.getText();
        String disciplina = tcmaDisciplina.getText();
        
        int i = 0;
        while(i < quantidadeAluno && !nome.equals(alunos[i].getNome())) {
            i++;
        }

        if (i < quantidadeAluno) {
            String informe = alunos[i].cancelarMatricula(disciplina);
            JOptionPane.showMessageDialog(jFrame, informe);
        } else {
            JOptionPane.showMessageDialog(jFrame, "Aluno não encontrado.");
        }
    }//GEN-LAST:event_bcmaCancelarMatriculaActionPerformed

    private void biaImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biaImprimirActionPerformed
        // TODO add your handling code here:
        String aluno = "";
        for (int i = 0; i < quantidadeAluno; i++) {
            aluno += alunos[i].imprime();
            taiaAreaTexto.setText(aluno);
        }
    }//GEN-LAST:event_biaImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaAcademico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JButton bcaCadastrar;
    private javax.swing.JButton bcmaCancelarMatricula;
    private javax.swing.JButton bcpCadastrar;
    private javax.swing.JButton beaExcluir;
    private javax.swing.JButton biaImprimir;
    private javax.swing.JButton bmaMatricular;
    private javax.swing.JButton bmpMatricular;
    private javax.swing.JLabel caCurso;
    private javax.swing.JLabel caEndereco;
    private javax.swing.JLabel caIdade;
    private javax.swing.JLabel caMatricula;
    private javax.swing.JLabel caNome;
    private javax.swing.JLabel caPeriodo;
    private javax.swing.JLabel cmaDisciplina;
    private javax.swing.JLabel cmaNome;
    private javax.swing.JLabel cpEndereco;
    private javax.swing.JLabel cpIdade;
    private javax.swing.JLabel cpNome;
    private javax.swing.JLabel eaNome;
    private javax.swing.JLabel maDisciplina;
    private javax.swing.JLabel maNome;
    private javax.swing.JLabel mpDisciplina;
    private javax.swing.JLabel mpNome;
    private javax.swing.JScrollPane siaAreaScroll;
    private javax.swing.JPanel tabCadastrarAluno;
    private javax.swing.JPanel tabCadastrarProfessor;
    private javax.swing.JPanel tabCancelarMatriculaAluno;
    private javax.swing.JPanel tabExcluirAluno;
    private javax.swing.JPanel tabImprimirAluno;
    private javax.swing.JPanel tabMatricularAluno;
    private javax.swing.JPanel tabMatricularProfessor;
    private javax.swing.JTextArea taiaAreaTexto;
    private javax.swing.JTextField tcaCurso;
    private javax.swing.JTextField tcaEndereco;
    private javax.swing.JTextField tcaIdade;
    private javax.swing.JTextField tcaMatricula;
    private javax.swing.JTextField tcaNome;
    private javax.swing.JTextField tcaPeriodo;
    private javax.swing.JTextField tcmaDisciplina;
    private javax.swing.JTextField tcmaNome;
    private javax.swing.JTextField tcpEndereco;
    private javax.swing.JTextField tcpIdade;
    private javax.swing.JTextField tcpNome;
    private javax.swing.JTextField teaNome;
    private javax.swing.JTextField tmaDisciplina;
    private javax.swing.JTextField tmaNome;
    private javax.swing.JTextField tmpDisciplina;
    private javax.swing.JTextField tmpNome;
    // End of variables declaration//GEN-END:variables
}
